In [1]:
import numpy as np


# NumPy arrays
> ### **Creating Arrays**

In [2]:
data = [1,2,3,4]
first_array = np.array(data)
first_array

array([1, 2, 3, 4])

In [3]:
data = [[1,2,3],
        [4,5,6],
        [7,8,9]]
my_array = np.array(data)
my_array

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

> ### **Dimensions and Shape**

In [4]:
oned = np.arange(21)
oned

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20])

In [5]:
list_o_lists =  [[1,2,3],[4,5,6],[7,8,9]]
twod = np.array(list_o_lists)
twod

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [6]:
np.ones(10)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [7]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [8]:
np.arange(15)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [11]:
twod.shape

(3, 3)

In [21]:
oned.shape


(21,)

In [22]:
twod.shape

(3, 3)

In [13]:
oned.ndim

1

In [24]:
twod.ndim

2

In [28]:
print(twod.size)

9


In [26]:
twod.shape

(3, 3)

In [27]:
oned = np.arange(12)

In [15]:
list_o_lists = [[1,2,3], [4,5,6],[7,8,9]]
twod = np.array(list_o_lists)
twod

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [29]:
twod = oned.reshape(3,4)
twod

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [31]:
twod.shape

(3, 4)

In [32]:
twod.ndim

2

In [33]:
twod.reshape(2,2,3)

array([[[ 0,  1,  2],
        [ 3,  4,  5]],

       [[ 6,  7,  8],
        [ 9, 10, 11]]])

> ### **Setting Data Type**

In [16]:
darray = np.arange(50)
darray

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33,
       34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49])

In [34]:
darray.dtype

dtype('int32')

In [35]:
darray.nbytes # check size of bytes

200

In [37]:
darray[12] = 0.4


In [39]:
darray[12] # will not return the float

0

> ### **Broadcasting**

In [41]:
A1 = np.array([[1,2,3],
              [4,5,6],
              [7,8,9]])

In [50]:
A1.shape

(3, 3)

In [42]:
A2 = np.array([[1,1,1],
              [1,1,1],
              [1,1,1]])

In [51]:
A1 + A2

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [52]:
A1 + 3

array([[ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [43]:
A3 = np.array([1,1,1])

In [53]:
A3.shape

(3,)

In [54]:
A1 + A3

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

In [47]:
A4 = np.arange(10).reshape(2,1,5)
A4

array([[[0, 1, 2, 3, 4]],

       [[5, 6, 7, 8, 9]]])

In [49]:
A5 = np.arange(14).reshape(2,7,1)
A5

array([[[ 0],
        [ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6]],

       [[ 7],
        [ 8],
        [ 9],
        [10],
        [11],
        [12],
        [13]]])

In [56]:
A6 = A4 + A5
A6

array([[[ 0,  1,  2,  3,  4],
        [ 1,  2,  3,  4,  5],
        [ 2,  3,  4,  5,  6],
        [ 3,  4,  5,  6,  7],
        [ 4,  5,  6,  7,  8],
        [ 5,  6,  7,  8,  9],
        [ 6,  7,  8,  9, 10]],

       [[12, 13, 14, 15, 16],
        [13, 14, 15, 16, 17],
        [14, 15, 16, 17, 18],
        [15, 16, 17, 18, 19],
        [16, 17, 18, 19, 20],
        [17, 18, 19, 20, 21],
        [18, 19, 20, 21, 22]]])

In [57]:
A6.shape

(2, 7, 5)

> ### **Matrix Operations**

In [61]:
M1 = np.arange(16).reshape(4,4)
M1

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [65]:
M1.transpose()

array([[ 0,  4,  8, 12],
       [ 1,  5,  9, 13],
       [ 2,  6, 10, 14],
       [ 3,  7, 11, 15]])

In [66]:
print(M1.diagonal())


[ 0  5 10 15]


In [64]:
M2 = np.arange(49).reshape(7,7)
M2

array([[ 0,  1,  2,  3,  4,  5,  6],
       [ 7,  8,  9, 10, 11, 12, 13],
       [14, 15, 16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25, 26, 27],
       [28, 29, 30, 31, 32, 33, 34],
       [35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48]])

In [67]:
M2.diagonal()

array([ 0,  8, 16, 24, 32, 40, 48])

In [63]:
M3 = np.arange(2,11).reshape(3,3)
M3

array([[ 2,  3,  4],
       [ 5,  6,  7],
       [ 8,  9, 10]])

## When to use the ndarry
> * Multi dimensional data
> * Single data type
> * Complex numerical calculations

## When to use the DataFrame pandas instead of ndarry
> * Two dimensiona data
> * Multiple data types
> * Data Analysis
> * Data visualization